name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_Deploy_LSTM_Modell:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r main/requirements

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3 
      
    - name: Build Docker image
      id: Docker_Build_LSTM
      uses: docker/build-push-action@v5
      with:
        context: main
        file: main/Dockerfile_LSTM.dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:main
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        kubeconfig: ${{ secrets.KUBECONFIG_FILE }}
    - name: Deploy to Kubernetes
      run: kubectl apply -f main/kubernetes.yaml

        
  build_Deploy_Transformer_Modell:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r main/requirements

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Build Docker image for Transformer_Modell
      id: Docker_Build_Transformer
      uses: docker/build-push-action@v5
      with:
        context: main
        file: main/Transformer_Dockerfile.dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        kubeconfig: ${{ secrets.KUBECONFIG_FILE }}
    - name: Deploy to Kubernetes
      run: kubectl apply -f main/kubernetes.yaml
       

      
  RUN_LSTM_Modell_to_Docker:
    runs-on: ubuntu-latest
    needs: build_Deploy_LSTM_Modell

    steps:
    - name: Run Docker Container für LSTM
      run: docker run -p 9090:80 sururikus/deneme2:main
      
  RUN_Transformer_Modell_to_Docker:
    runs-on: ubuntu-latest
    needs: build_Deploy_Transformer_Modell

    steps:
    - name: Run Docker Container für TRANSFORMER
      run: docker run -p 9091:80 sururikus/deneme2:latest -p
  
      
        
