name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_LSTM_Modell:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r main/requirements

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta1
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: sururikus/deneme2
      
    - name: Build Docker image
      id: Docker_Build_LSTM
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: main
        file: main/Dockerfile_LSTM.dockerfile
        push: false
        tags: ${{ steps.meta1.outputs.tags }}
        labels: ${{ steps.meta1.outputs.labels }}
  build_Transformer_Modell:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r main/requirements

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta2
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: sururikus/deneme2
        
    - name: Build Docker image for Transformer_Modell
      id: Docker_Build_Transformer
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: main
        file: main/Transformer_Dockerfile.dockerfile
        push: false
        tags: ${{ steps.meta2.outputs.tags }}
        labels: ${{ steps.meta2.outputs.labels }}
        
  Deploy_LSTM_Modell_to_Docker:
    runs-on: ubuntu-latest
    needs: build_LSTM_Modell

    steps:
      - name: Log in to Dicker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Image to Docker Hub
        run: docker push sururikus/deneme2:${{ steps.meta1.outputs.tags }}
      
  Deploy_Transformer_Modell_to_Docker:
    runs-on: ubuntu-latest
    needs: build_Transformer_Modell
    
    steps:
      - name: Log in to Dicker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Image to Docker Hub
        run: docker push sururikus/deneme2:${{ steps.meta2.outputs.tags }}
      
  RUN_LSTM_Modell_to_Docker:
    runs-on: ubuntu-latest
    needs: build_LSTM_Modell

    steps:
    - name: Run Docker Container für LSTM
      run: docker run sururikus/deneme2:${{ steps.meta1.outputs.tags }}
      
  RUN_Transformer_Modell_to_Docker:
    runs-on: ubuntu-latest
    needs: build_Transformer_Modell

    steps:
    - name: Run Docker Container für LSTM
      run: docker run sururikus/deneme2:${{ steps.meta2.outputs.tags }}
  
      
        
